/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData gridactive = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gridinactive = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profileactive = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profileinactive = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swipenotselected = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swipeselected = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swipingactive = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swipinginactive = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData testing = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
